import { VisaStatus } from "./PassportIndex";

export interface Destination {
  country: string;
  code: string;
  status: VisaStatus;
  duration?: string;
}

export interface PassportData {
  rank: number;
  score: number;
  stats: {
    free: number;
    voa: number;
    eta: number;
    required: number;
  };
  destinations: Destination[];
}

export const PASSPORT_DATA: Record<string, PassportData> = {
  "Algérien": {
    rank: 83,
    score: 55,
    stats: { free: 21, voa: 32, eta: 2, required: 143 },
    destinations: [
      { country: "Fiji", code: "FI", status: "required" },
      { country: "Tanzania", code: "TA", status: "required" },
      { country: "W. Sahara", code: "W.", status: "required" },
      { country: "United States of America", code: "UN", status: "required" },
      { country: "Kazakhstan", code: "KA", status: "required" },
      { country: "Uzbekistan", code: "UZ", status: "required" },
      { country: "Papua New Guinea", code: "PA", status: "required" },
      { country: "Chile", code: "CH", status: "required" },
      { country: "Dem. Rep. Congo", code: "DE", status: "required" },
      { country: "Somalia", code: "SO", status: "required" },
      { country: "Kenya", code: "KE", status: "required" },
      { country: "Sudan", code: "SU", status: "required" },
      { country: "Chad", code: "CH", status: "required" },
      { country: "Haiti", code: "HA", status: "required" },
      { country: "Dominican Rep.", code: "DO", status: "required" },
      { country: "Bahamas", code: "BA", status: "required" },
      { country: "Falkland Is.", code: "FA", status: "required" },
      { country: "Norway", code: "NO", status: "required" },
      { country: "Greenland", code: "GR", status: "required" },
      { country: "Fr. S. Antarctic Lands", code: "FR", status: "required" },
      { country: "Timor-Leste", code: "TI", status: "required" },
      { country: "Lesotho", code: "LE", status: "required" },
      { country: "Uruguay", code: "UR", status: "required" },
      { country: "Bolivia", code: "BO", status: "required" },
      { country: "Peru", code: "PE", status: "required" },
      { country: "Colombia", code: "CO", status: "required" },
      { country: "Panama", code: "PA", status: "required" },
      { country: "Costa Rica", code: "CO", status: "required" },
      { country: "Nicaragua", code: "NI", status: "required" },
      { country: "Honduras", code: "HO", status: "required" },
      { country: "El Salvador", code: "EL", status: "required" },
      { country: "Guatemala", code: "GU", status: "required" },
      { country: "Belize", code: "BE", status: "required" },
      { country: "Venezuela", code: "VE", status: "required" },
      { country: "Guyana", code: "GU", status: "required" },
      { country: "Suriname", code: "SU", status: "required" },
      { country: "Puerto Rico", code: "PU", status: "required" },
      { country: "Jamaica", code: "JA", status: "required" },
      { country: "Cuba", code: "CU", status: "required" },
      { country: "Zimbabwe", code: "ZI", status: "required" },
      { country: "Botswana", code: "BO", status: "required" },
      { country: "Namibia", code: "NA", status: "required" },
      { country: "Benin", code: "BE", status: "required" },
      { country: "Niger", code: "NI", status: "required" },
      { country: "Nigeria", code: "NI", status: "required" },
      { country: "Cameroon", code: "CA", status: "required" },
      { country: "Togo", code: "TO", status: "required" },
      { country: "Ghana", code: "GH", status: "required" },
      { country: "Côte d'Ivoire", code: "CÔ", status: "required" },
      { country: "Guinea-Bissau", code: "GU", status: "required" },
      { country: "Liberia", code: "LI", status: "required" },
      { country: "Sierra Leone", code: "SI", status: "required" },
      { country: "Burkina Faso", code: "BU", status: "required" },
      { country: "Central African Rep.", code: "CE", status: "required" },
      { country: "Congo", code: "CO", status: "required" },
      { country: "Gabon", code: "GA", status: "required" },
      { country: "Eq. Guinea", code: "EQ", status: "required" },
      { country: "Zambia", code: "ZA", status: "required" },
      { country: "Malawi", code: "MA", status: "required" },
      { country: "Mozambique", code: "MO", status: "required" },
      { country: "eSwatini", code: "ES", status: "required" },
      { country: "Angola", code: "AN", status: "required" },
      { country: "Burundi", code: "BU", status: "required" },
      { country: "Israel", code: "IS", status: "required" },
      { country: "Lebanon", code: "LE", status: "required" },
      { country: "Madagascar", code: "MA", status: "required" },
      { country: "Palestine", code: "PA", status: "required" },
      { country: "Gambia", code: "GA", status: "required" },
      { country: "Algeria", code: "AL", status: "required" },
      { country: "Jordan", code: "JO", status: "required" },
      { country: "Qatar", code: "QA", status: "required" },
      { country: "Kuwait", code: "KU", status: "required" },
      { country: "Iraq", code: "IR", status: "required" },
      { country: "Oman", code: "OM", status: "required" },
      { country: "Vanuatu", code: "VA", status: "required" },
      { country: "Cambodia", code: "CA", status: "required" },
      { country: "Thailand", code: "TH", status: "required" },
      { country: "Laos", code: "LA", status: "required" },
      { country: "Myanmar", code: "MY", status: "required" },
      { country: "Vietnam", code: "VI", status: "required" },
      { country: "North Korea", code: "NO", status: "required" },
      { country: "Mongolia", code: "MO", status: "required" },
      { country: "Bangladesh", code: "BA", status: "required" },
      { country: "Bhutan", code: "BH", status: "required" },
      { country: "Nepal", code: "NE", status: "required" },
      { country: "Pakistan", code: "PA", status: "required" },
      { country: "Afghanistan", code: "AF", status: "required" },
      { country: "Tajikistan", code: "TA", status: "required" },
      { country: "Kyrgyzstan", code: "KY", status: "required" },
      { country: "Turkmenistan", code: "TU", status: "required" },
      { country: "Iran", code: "IR", status: "required" },
      { country: "Armenia", code: "AR", status: "required" },
      { country: "Sweden", code: "SW", status: "required" },
      { country: "Belarus", code: "BE", status: "required" },
      { country: "Ukraine", code: "UK", status: "required" },
      { country: "Poland", code: "PO", status: "required" },
      { country: "Austria", code: "AU", status: "required" },
      { country: "Hungary", code: "HU", status: "required" },
      { country: "Moldova", code: "MO", status: "required" },
      { country: "Romania", code: "RO", status: "required" },
      { country: "Lithuania", code: "LI", status: "required" },
      { country: "Latvia", code: "LA", status: "required" },
      { country: "Estonia", code: "ES", status: "required" },
      { country: "Bulgaria", code: "BU", status: "required" },
      { country: "Greece", code: "GR", status: "required" },
      { country: "Albania", code: "AL", status: "required" },
      { country: "Croatia", code: "CR", status: "required" },
      { country: "Switzerland", code: "SW", status: "required" },
      { country: "Luxembourg", code: "LU", status: "required" },
      { country: "Belgium", code: "BE", status: "required" },
      { country: "Netherlands", code: "NE", status: "required" },
      { country: "Portugal", code: "PO", status: "required" },
      { country: "Ireland", code: "IR", status: "required" },
      { country: "New Caledonia", code: "NE", status: "required" },
      { country: "Solomon Is.", code: "SO", status: "required" },
      { country: "New Zealand", code: "NE", status: "required" },
      { country: "Taiwan", code: "TA", status: "required" },
      { country: "Denmark", code: "DE", status: "required" },
      { country: "Iceland", code: "IC", status: "required" },
      { country: "Azerbaijan", code: "AZ", status: "required" },
      { country: "Georgia", code: "GE", status: "required" },
      { country: "Philippines", code: "PH", status: "required" },
      { country: "Brunei", code: "BR", status: "required" },
      { country: "Slovenia", code: "SL", status: "required" },
      { country: "Finland", code: "FI", status: "required" },
      { country: "Slovakia", code: "SL", status: "required" },
      { country: "Czechia", code: "CZ", status: "required" },
      { country: "Eritrea", code: "ER", status: "required" },
      { country: "Paraguay", code: "PA", status: "required" },
      { country: "Antarctica", code: "AN", status: "required" },
      { country: "N. Cyprus", code: "N.", status: "required" },
      { country: "Cyprus", code: "CY", status: "required" },
      { country: "Egypt", code: "EG", status: "required" },
      { country: "Libya", code: "LI", status: "required" },
      { country: "Ethiopia", code: "ET", status: "required" },
      { country: "Djibouti", code: "DJ", status: "required" },
      { country: "Somaliland", code: "SO", status: "required" },
      { country: "Uganda", code: "UG", status: "required" },
      { country: "Rwanda", code: "RW", status: "required" },
      { country: "Bosnia and Herz.", code: "BO", status: "required" },
      { country: "Macedonia", code: "MA", status: "required" },
      { country: "Serbia", code: "SE", status: "required" },
      { country: "Montenegro", code: "MO", status: "required" },
      { country: "Kosovo", code: "KO", status: "required" },
      { country: "Trinidad and Tobago", code: "TR", status: "required" },
      { country: "S. Sudan", code: "S.", status: "required" },
      { country: "Malaysia", code: "MY", status: "free", duration: "90 jours" },
      { country: "Ecuador", code: "EC", status: "free", duration: "90 jours" },
      { country: "Indonesia", code: "ID", status: "free", duration: "30 jours" },
      { country: "Tunisia", code: "TN", status: "free", duration: "90 jours" },
      { country: "Morocco", code: "MA", status: "free", duration: "90 jours" },
      { country: "Mali", code: "ML", status: "free", duration: "90 jours" },
      { country: "Senegal", code: "SN", status: "free", duration: "90 jours" },
      { country: "Guinea", code: "GN", status: "free", duration: "90 jours" },
      { country: "Mauritania", code: "MR", status: "free", duration: "90 jours" },
      { country: "Syria", code: "SY", status: "free", duration: "90 jours" },
      { country: "Yemen", code: "YE", status: "voa", duration: "90 jours" },
      { country: "Maldives", code: "MV", status: "voa", duration: "30 jours" },
      { country: "Sri Lanka", code: "LK", status: "eta", duration: "30 jours" },
      { country: "Turkey", code: "TR", status: "required" },
      { country: "France", code: "FR", status: "required" },
      { country: "Spain", code: "ES", status: "required" },
      { country: "United Arab Emirates", code: "AE", status: "required" },
      { country: "Saudi Arabia", code: "SA", status: "required" },
      { country: "United Kingdom", code: "GB", status: "required" },
      { country: "United States", code: "US", status: "required" },
      { country: "China", code: "CN", status: "required" },
      { country: "Brazil", code: "BR", status: "required" },
      { country: "Russia", code: "RU", status: "required" },
      { country: "Australia", code: "AU", status: "required" },
      { country: "India", code: "IN", status: "required" },
      { country: "Canada", code: "CA", status: "required" },
      { country: "Germany", code: "DE", status: "required" },
      { country: "Italy", code: "IT", status: "required" },
      { country: "Japan", code: "JP", status: "required" },
      { country: "South Korea", code: "KR", status: "required" },
      { country: "South Africa", code: "ZA", status: "required" },
      { country: "Argentina", code: "AR", status: "required" },
      { country: "Mexico", code: "MX", status: "required" },
    ]
  },
  "Français": {
    rank: 3,
    score: 177,
    stats: { free: 124, voa: 43, eta: 10, required: 21 },
    destinations: [
      { country: "United States", code: "US", status: "eta", duration: "90 jours" },
      { country: "Japan", code: "JP", status: "free", duration: "90 jours" },
      { country: "Brazil", code: "BR", status: "free", duration: "90 jours" },
      { country: "Canada", code: "CA", status: "eta", duration: "180 jours" },
      { country: "United Arab Emirates", code: "AE", status: "free", duration: "90 jours" },
      { country: "Algeria", code: "DZ", status: "required" },
      { country: "Russia", code: "RU", status: "required" },
      { country: "China", code: "CN", status: "free", duration: "15 jours" },
      { country: "India", code: "IN", status: "eta", duration: "30 jours" },
      { country: "Saudi Arabia", code: "SA", status: "voa", duration: "90 jours" },
      { country: "Australia", code: "AU", status: "eta", duration: "90 jours" },
    ]
  },
  "Émirati": {
    rank: 1,
    score: 179,
    stats: { free: 133, voa: 46, eta: 0, required: 19 },
    destinations: [
      { country: "France", code: "FR", status: "free", duration: "90 jours" },
      { country: "United Kingdom", code: "GB", status: "free", duration: "180 jours" },
      { country: "Saudi Arabia", code: "SA", status: "free", duration: "90 jours" },
      { country: "Japan", code: "JP", status: "free", duration: "30 jours" },
      { country: "United States", code: "US", status: "required" },
      { country: "Algeria", code: "DZ", status: "required" },
      { country: "China", code: "CN", status: "free", duration: "30 jours" },
      { country: "Russia", code: "RU", status: "free", duration: "90 jours" },
      { country: "India", code: "IN", status: "required" },
      { country: "Brazil", code: "BR", status: "free", duration: "90 jours" },
      { country: "Australia", code: "AU", status: "required" },
      { country: "Canada", code: "CA", status: "required" }
    ]
  }
};
